{
    "schema_version": "1.6.0",
    "id": "OESA-2023-1088",
    "modified": "2023-02-17T00:00:00Z",
    "published": "2023-02-17T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2023-23931"
    ],
    "summary": "python-cryptography security update",
    "details": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers.\r\n\r\nSecurity Fix(es):\r\n\r\ncryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.(CVE-2023-23931)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-22.03-LTS",
                "name": "python-cryptography",
                "purl": "pkg:rpm/python-cryptography@3.3.1-5.oe2203"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "3.3.1-5.oe2203",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "python3-cryptography-3.3.1-5.oe2203.aarch64.rpm",
                    "python-cryptography-debuginfo-3.3.1-5.oe2203.aarch64.rpm",
                    "python-cryptography-debugsource-3.3.1-5.oe2203.aarch64.rpm"
                ],
                "noarch": [
                    "python-cryptography-help-3.3.1-5.oe2203.noarch.rpm"
                ],
                "src": [
                    "python-cryptography-3.3.1-5.oe2203.src.rpm"
                ],
                "x86_64": [
                    "python-cryptography-debuginfo-3.3.1-5.oe2203.x86_64.rpm",
                    "python-cryptography-debugsource-3.3.1-5.oe2203.x86_64.rpm",
                    "python3-cryptography-3.3.1-5.oe2203.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-23931"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "Medium"
    }
}