{
    "schema_version": "1.6.0",
    "id": "OESA-2024-2166",
    "modified": "2024-09-20T00:00:00Z",
    "published": "2024-09-20T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2024-5953",
        "CVE-2024-6237"
    ],
    "summary": "three-eight-nine-ds-base security update",
    "details": "389-ds-base is an LDAPv3 compliant server which includes the LDAP server and command line utilities for server administration.\r\n\r\nSecurity Fix(es):\r\n\r\nA denial of service vulnerability was found in the 389-ds-base LDAP server. This issue may allow an authenticated user to cause a server denial of service while attempting to log in with a user with a malformed hash in their password.(CVE-2024-5953)\r\n\r\nA flaw was found in the 389 Directory Server. This flaw allows an unauthenticated user to cause a systematic server crash while sending a specific extended search request, leading to a denial of service.(CVE-2024-6237)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-24.03-LTS",
                "name": "three-eight-nine-ds-base",
                "purl": "pkg:rpm/three-eight-nine-ds-base@389-ds-base-3.1.1-1.oe2403"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "389-ds-base-3.1.1-1.oe2403",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "389-ds-base-3.1.1-1.oe2403.aarch64.rpm",
                    "389-ds-base-debuginfo-3.1.1-1.oe2403.aarch64.rpm",
                    "389-ds-base-debugsource-3.1.1-1.oe2403.aarch64.rpm",
                    "389-ds-base-devel-3.1.1-1.oe2403.aarch64.rpm",
                    "389-ds-base-help-3.1.1-1.oe2403.aarch64.rpm",
                    "389-ds-base-snmp-3.1.1-1.oe2403.aarch64.rpm"
                ],
                "noarch": [
                    "cockpit-389-ds-3.1.1-1.oe2403.noarch.rpm",
                    "python3-lib389-3.1.1-1.oe2403.noarch.rpm"
                ],
                "src": [
                    "389-ds-base-3.1.1-1.oe2403.src.rpm"
                ],
                "x86_64": [
                    "389-ds-base-3.1.1-1.oe2403.x86_64.rpm",
                    "389-ds-base-debuginfo-3.1.1-1.oe2403.x86_64.rpm",
                    "389-ds-base-debugsource-3.1.1-1.oe2403.x86_64.rpm",
                    "389-ds-base-devel-3.1.1-1.oe2403.x86_64.rpm",
                    "389-ds-base-help-3.1.1-1.oe2403.x86_64.rpm",
                    "389-ds-base-snmp-3.1.1-1.oe2403.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-5953"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6237"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "Medium"
    }
}