{
    "schema_version": "1.6.0",
    "id": "OESA-2024-1940",
    "modified": "2024-08-02T00:00:00Z",
    "published": "2024-08-02T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2024-0397",
        "CVE-2024-4032"
    ],
    "summary": "python3 security update",
    "details": "Python combines remarkable power with very clear syntax. It has modules, classes, exceptions, very high level dynamic data types, and dynamic typing. There are interfaces to many system calls and libraries, as well as to various windowing systems. New built-in modules are easily written in C or C++ (or other languages, depending on the chosen implementation). Python is also usable as an extension language for applications written in other languages that need easy-to-use scripting or automation interfaces.\r\n\r\nSecurity Fix(es):\r\n\r\nA defect was discovered in the Python “ssl” module where there is a memory\nrace condition with the ssl.SSLContext methods “cert_store_stats()” and\n“get_ca_certs()”. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.(CVE-2024-0397)\r\n\r\nThe “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\r\n\r\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.(CVE-2024-4032)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-24.03-LTS",
                "name": "python3",
                "purl": "pkg:rpm/python3@3.11.6-4.oe2403"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "3.11.6-4.oe2403",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "python3-devel-3.11.6-4.oe2403.aarch64.rpm",
                    "python3-debuginfo-3.11.6-4.oe2403.aarch64.rpm",
                    "python3-unversioned-command-3.11.6-4.oe2403.aarch64.rpm",
                    "python3-debugsource-3.11.6-4.oe2403.aarch64.rpm",
                    "python3-tkinter-3.11.6-4.oe2403.aarch64.rpm",
                    "python3-debug-3.11.6-4.oe2403.aarch64.rpm",
                    "python3-3.11.6-4.oe2403.aarch64.rpm"
                ],
                "noarch": [
                    "python3-help-3.11.6-4.oe2403.noarch.rpm"
                ],
                "src": [
                    "python3-3.11.6-4.oe2403.src.rpm"
                ],
                "x86_64": [
                    "python3-unversioned-command-3.11.6-4.oe2403.x86_64.rpm",
                    "python3-debuginfo-3.11.6-4.oe2403.x86_64.rpm",
                    "python3-debugsource-3.11.6-4.oe2403.x86_64.rpm",
                    "python3-tkinter-3.11.6-4.oe2403.x86_64.rpm",
                    "python3-devel-3.11.6-4.oe2403.x86_64.rpm",
                    "python3-debug-3.11.6-4.oe2403.x86_64.rpm",
                    "python3-3.11.6-4.oe2403.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-0397"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-4032"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "High"
    }
}