{
    "schema_version": "1.6.0",
    "id": "OESA-2024-2192",
    "modified": "2024-09-27T00:00:00Z",
    "published": "2024-09-27T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2023-6597",
        "CVE-2024-3219",
        "CVE-2024-6232"
    ],
    "summary": "python3 security update",
    "details": "Python combines remarkable power with very clear syntax. It has modules, classes, exceptions, very high level dynamic data types, and dynamic typing. There are interfaces to many system calls and libraries, as well as to various windowing systems. New built-in modules are easily written in C or C++ (or other languages, depending on the chosen implementation). Python is also usable as an extension language for applications written in other languages that need easy-to-use scripting or automation interfaces.\r\n\r\nSecurity Fix(es):\r\n\r\nAn issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\r\n\r\nThe tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.\n(CVE-2023-6597)\r\n\r\nThere is a MEDIUM severity vulnerability affecting CPython.\r\n\r\nThe\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\r\n\r\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.(CVE-2024-3219)\r\n\r\nThere is a MEDIUM severity vulnerability affecting CPython.\r\n\r\n\r\n\r\n\r\n\r\nRegular expressions that allowed excessive backtracking during tarfile.TarFile header parsing are vulnerable to ReDoS via specifically-crafted tar archives.(CVE-2024-6232)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-22.03-LTS-SP1",
                "name": "python3",
                "purl": "pkg:rpm/python3@3.9.9-32.oe2203sp1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "3.9.9-32.oe2203sp1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "python3-3.9.9-32.oe2203sp1.aarch64.rpm",
                    "python3-debug-3.9.9-32.oe2203sp1.aarch64.rpm",
                    "python3-debuginfo-3.9.9-32.oe2203sp1.aarch64.rpm",
                    "python3-debugsource-3.9.9-32.oe2203sp1.aarch64.rpm",
                    "python3-devel-3.9.9-32.oe2203sp1.aarch64.rpm",
                    "python3-unversioned-command-3.9.9-32.oe2203sp1.aarch64.rpm"
                ],
                "noarch": [
                    "python3-help-3.9.9-32.oe2203sp1.noarch.rpm"
                ],
                "src": [
                    "python3-3.9.9-32.oe2203sp1.src.rpm"
                ],
                "x86_64": [
                    "python3-3.9.9-32.oe2203sp1.x86_64.rpm",
                    "python3-debug-3.9.9-32.oe2203sp1.x86_64.rpm",
                    "python3-debuginfo-3.9.9-32.oe2203sp1.x86_64.rpm",
                    "python3-debugsource-3.9.9-32.oe2203sp1.x86_64.rpm",
                    "python3-devel-3.9.9-32.oe2203sp1.x86_64.rpm",
                    "python3-unversioned-command-3.9.9-32.oe2203sp1.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6597"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3219"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6232"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "High"
    }
}