{"schema_version":"1.6.0","id":"OESA-2022-1522","modified":"2022-02-11T11:31:15Z","published":"2022-02-11T11:31:15Z","related":["CVE-2021-41495","CVE-2021-34141"],"summary":"numpy security update","details":"A fast multidimensional array facility for Python.\r\n\r\nSecurity Fix(es):\r\n\r\nNull Pointer Dereference vulnerability exists in numpy.sort in NumPy &amp;lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays.(CVE-2021-41495)\r\n\r\nAn incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. NOTE: the vendor states that this reported code behavior is &quot;completely harmless.&quot;(CVE-2021-34141)","affected":[{"package":{"ecosystem":"openEuler-20.03-LTS-SP1","name":"numpy","purl":"pkg:rpm/openEuler/numpy&distro=openEuler-20.03-LTS-SP1"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"1.16.5-6.oe1"}]}],"ecosystem_specific":{"aarch64":["python3-numpy-1.16.5-6.oe1.aarch64.rpm","python3-numpy-f2py-1.16.5-6.oe1.aarch64.rpm","numpy-debuginfo-1.16.5-6.oe1.aarch64.rpm","numpy-debugsource-1.16.5-6.oe1.aarch64.rpm","python2-numpy-1.16.5-6.oe1.aarch64.rpm","python2-numpy-f2py-1.16.5-6.oe1.aarch64.rpm"],"src":["numpy-1.16.5-6.oe1.src.rpm"],"x86_64":["numpy-debugsource-1.16.5-6.oe1.x86_64.rpm","python3-numpy-1.16.5-6.oe1.x86_64.rpm","python2-numpy-f2py-1.16.5-6.oe1.x86_64.rpm","numpy-debuginfo-1.16.5-6.oe1.x86_64.rpm","python2-numpy-1.16.5-6.oe1.x86_64.rpm","python3-numpy-f2py-1.16.5-6.oe1.x86_64.rpm"]}},{"package":{"ecosystem":"openEuler-20.03-LTS-SP2","name":"numpy","purl":"pkg:rpm/openEuler/numpy&distro=openEuler-20.03-LTS-SP2"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"1.16.5-6.oe1"}]}],"ecosystem_specific":{"aarch64":["numpy-debuginfo-1.16.5-6.oe1.aarch64.rpm","python2-numpy-1.16.5-6.oe1.aarch64.rpm","python3-numpy-1.16.5-6.oe1.aarch64.rpm","numpy-debugsource-1.16.5-6.oe1.aarch64.rpm","python3-numpy-f2py-1.16.5-6.oe1.aarch64.rpm","python2-numpy-f2py-1.16.5-6.oe1.aarch64.rpm"],"src":["numpy-1.16.5-6.oe1.src.rpm"],"x86_64":["python2-numpy-f2py-1.16.5-6.oe1.x86_64.rpm","numpy-debuginfo-1.16.5-6.oe1.x86_64.rpm","python3-numpy-1.16.5-6.oe1.x86_64.rpm","python3-numpy-f2py-1.16.5-6.oe1.x86_64.rpm","python2-numpy-1.16.5-6.oe1.x86_64.rpm","numpy-debugsource-1.16.5-6.oe1.x86_64.rpm"]}},{"package":{"ecosystem":"openEuler-20.03-LTS-SP3","name":"numpy","purl":"pkg:rpm/openEuler/numpy&distro=openEuler-20.03-LTS-SP3"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"1.16.5-6.oe1"}]}],"ecosystem_specific":{"aarch64":["python2-numpy-1.16.5-6.oe1.aarch64.rpm","numpy-debugsource-1.16.5-6.oe1.aarch64.rpm","numpy-debuginfo-1.16.5-6.oe1.aarch64.rpm","python3-numpy-1.16.5-6.oe1.aarch64.rpm","python2-numpy-f2py-1.16.5-6.oe1.aarch64.rpm","python3-numpy-f2py-1.16.5-6.oe1.aarch64.rpm"],"src":["numpy-1.16.5-6.oe1.src.rpm"],"x86_64":["python2-numpy-f2py-1.16.5-6.oe1.x86_64.rpm","numpy-debuginfo-1.16.5-6.oe1.x86_64.rpm","numpy-debugsource-1.16.5-6.oe1.x86_64.rpm","python2-numpy-1.16.5-6.oe1.x86_64.rpm","python3-numpy-f2py-1.16.5-6.oe1.x86_64.rpm","python3-numpy-1.16.5-6.oe1.x86_64.rpm"]}}],"references":[{"type":"ADVISORY","url":"https://www.openeuler.org/en/security/safety-bulletin/detail.html?id=openEuler-SA-2022-1522"},{"type":"ADVISORY","url":"https://nvd.nist.gov/vuln/detail/CVE-2021-41495"},{"type":"ADVISORY","url":"https://nvd.nist.gov/vuln/detail/CVE-2021-34141"}],"database_specific":{"severity":"High"}}
