{"schema_version":"1.6.0","id":"OESA-2024-1948","modified":"2024-08-02T11:33:01Z","published":"2024-08-02T11:33:01Z","related":["CVE-2024-38875"],"summary":"python-django security update","details":"Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.\r\n\r\nSecurity Fix(es):\r\n\r\nAn issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.(CVE-2024-38875)","affected":[{"package":{"ecosystem":"openEuler-24.03-LTS","name":"python-django","purl":"pkg:rpm/openEuler/python-django&distro=openEuler-24.03-LTS"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"4.2.14-1.oe2403"}]}],"ecosystem_specific":{"noarch":["python3-Django-4.2.14-1.oe2403.noarch.rpm","python-django-help-4.2.14-1.oe2403.noarch.rpm"],"src":["python-django-4.2.14-1.oe2403.src.rpm"]}}],"references":[{"type":"ADVISORY","url":"https://www.openeuler.org/en/security/security-bulletins/detail?id=openEuler-SA-2024-1948"},{"type":"ADVISORY","url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"}],"database_specific":{"severity":"High"}}
