{"schema_version":"1.6.0","id":"OESA-2022-1971","modified":"2022-09-30T11:31:34Z","published":"2022-09-30T11:31:34Z","related":["CVE-2022-36087"],"summary":"python-oauthlib security update","details":"\r\n\r\nSecurity Fix(es):\r\n\r\nOAuthLib is an implementation of the OAuth request-signing logic for Python 3.6+. In OAuthLib versions 3.1.1 until 3.2.1, an attacker providing malicious redirect uri can cause denial of service. An attacker can also leverage usage of `uri_validate` functions depending where it is used. OAuthLib applications using OAuth2.0 provider support or use directly `uri_validate` are affected by this issue. Version 3.2.1 contains a patch. There are no known workarounds.(CVE-2022-36087)","affected":[{"package":{"ecosystem":"openEuler-22.03-LTS","name":"python-oauthlib","purl":"pkg:rpm/openEuler/python-oauthlib&distro=openEuler-22.03-LTS"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"3.1.1-3.oe2203"}]}],"ecosystem_specific":{"noarch":["python3-oauthlib-3.1.1-3.oe2203.noarch.rpm"],"src":["python-oauthlib-3.1.1-3.oe2203.src.rpm"]}}],"references":[{"type":"ADVISORY","url":"https://www.openeuler.org/en/security/safety-bulletin/detail.html?id=openEuler-SA-2022-1971"},{"type":"ADVISORY","url":"https://nvd.nist.gov/vuln/detail/CVE-2022-36087"}],"database_specific":{"severity":"Medium"}}
